### PR TITLE
Math Magicians: setup

### PR DESCRIPTION
**Pull request by Yidnekachew-cmd**
### In this branch, I have added the following:

- [ ] Create a React application using [Create React App](https://create-react-app.dev/).
- [ ] The application runs in the browser without errors.
- [ ] I have used correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
- [ ] I have added the [react-redux](https://github.com/microverseinc/linters-config/tree/master/react-redux) linters setup.

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Yidnekachew, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure to add a professional ReadMe to this project  via [this link](https://github.com/microverseinc/readme-template), which should comply with the following standard(s):
- [x] All main headers from the [ReadMe template](https://github.com/microverseinc/readme-template) should be present in your ReadMe, only the _FAQ_ section is optional.
- [x]  The _Future Features_ section of your ReadMe includes 1-3 potential features to be added later. 
- [x] Kindly ensure to remove the Microverse template logo. Optionally, you can replace it with your own logo if you have one.
- [x] Remove Live demo link from the ReadMe if app is not yet deployed.
- [x] Kindly ensure that provided placeholder texts/ guide instructions are removed and/or replaced with appropriate contents applicable under each section of your ReadMe. Similarly, kindly also remove guide notes for _license_ creation under the _license_ section.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Yidnekachew-cmd** [comment]
Hello @rloterh, Thank You for your comments! 🤗

**Review by KayLemba — APPROVED** [review]
[[# STATUS: APPROVED :green_circle: :clap: 

Hello  @Yidnekachew-cmd     , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] Professional README 💯
- [x] Your work is well documented 🥇 
- [x] React correctly setup 🥇  










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



well-1

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]s

**Comment by Yidnekachew-cmd** [comment]
Hi @KayLemba, Thabk You! 🤗

**Pull request merged**
